# Generated by Django 3.1.7 on 2021-05-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0002_user_details_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='access_token',
            field=models.CharField(default='', max_length=20000000000),
        ),
    ]
