# Generated by Django 3.1.7 on 2021-05-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0003_auto_20210520_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
