# Generated by Django 3.1.7 on 2021-05-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0004_user_details_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='access_token_secret',
            field=models.CharField(default='', max_length=20000000000),
        ),
        migrations.AddField(
            model_name='user_details',
            name='iaccess_token',
            field=models.CharField(default='', max_length=20000000000),
        ),
        migrations.AddField(
            model_name='user_details',
            name='insta_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='tweet_access_token',
            field=models.CharField(default='', max_length=20000000000),
        ),
    ]
